CSS-Tricks/conferences

site/conferences/2019-jsconf-budapest.md
Awesome Job coming up with this site! 🙌 I'm adding JSConf Budapest.
=> Add JSConf Budapest

site/conferences/2019-webunleashed-toronto.md
Of all the conferences, I clicked on this one as I'm going to be in Toronto on the dates it was showing, but when I clicked through to the conference site the dates were different! Damn!
Anyhow.. corrected the dates for you.
=> Corrected dates

dist/index.html, package-lock.json, site/conferences/2019-rustbelt-refresh-cleveland.md
I ran this locally to make sure I didn't add too long of a blurb for Rustbelt Refresh in Cleveland, on March 8th. The pull request looks like it added a bunch of additional stuff because the fork must not have contained the generated files.
Let me know how you want me to handle that, if at all.
Thanks!
=> Rustbelt Refresh

dist/index.html, site/conferences/2019-wdcode19-melbourne.md, site/conferences/2019-wddesign19-melbourne.md, site/conferences/2019-wdsummit19-sydney.md
Adding the 3 *code/design-ey* conferences organised by John Allsopp here in Australia.
=> 🇦🇺 Web Directions conferences in Australia!

site/conferences/2019-devfestkc-kansascity.md
=> Added DevFest KC 2019

dist/index.html, site/_includes/css/list.css
The link color in list view is pretty much in default mode :sweat_smile: 
So, I used the dark CSS variable
=> Fix Link Colors in List

site/conferences/2019-refactr-atlanta.md
=> Add Refactr.Tech conference

site/conferences/2019-jsconfasia-singapore.md
Add [JSConf.Asia](https://2019.jsconf.asia/).
=> Add JSConf.Asia

site/conferences/2019-reactday-newyork.md
=> Add react day new york 2019

site/_includes/conference.njk, site/index.njk
Using some ARIA attributes to enhance accessiblity of the site.
=> Adding accessibility for screen readers

site/conferences/2019-yglfconf-vilnius.md
https://lithuania.yglfconf.com
=> added YGLF Lithuania

package-lock.json, site/conferences/2019-reactfoo-bangalore.md
Looks like the last conference to be added referred to in #12 
The rest not checked off look to be already added!
=> adds reactfoo 2019

.eleventy.js, site/_includes/conference.njk
Time element was throwing errors in the HTML validator.
=> Addressing HTML time element

site/conferences/2019-reactloop-chicago.md
This PR adds React Loop 2019.  While we have adopted the conference code of conduct we have added language on our site that clearly establishes how to contact us with concerns or questions.  We've also included actionable steps for conference participants to take if they identify a situation where the CoC is not being followed.  https://reactloop.com/conduct
=> add React Loop 2019

site/conferences/2019-jsheroes-romania.md
Took the stab of adding from your list #12
=> Add JSHeroes

site/conferences/2019-yglf-isreal.md
=> Add YGLF Code Camp

site/_includes/css/list.css
=> Hide calendar icon in list view

site/conferences/2019-artifact-austin.md
- link to CoC
- updated date (to include workshops)
- updated description
=> Update ARTIFACT Conference listing

site/conferences/2019-nejsconf.md
This is a good tech stack you got here
=> Adds NEJS CONF 2019

netlify.toml
Make build run eleventy and temp install function modules `postbuild` script =)
Missing part of https://github.com/CSS-Tricks/conferences/pull/113
=> Update build command to `npm run build`

site/conferences/2019-ReactiveConf-Prague.md
=> Changed file to .md and fixed a typo for Reactive Conf

site/conferences/2019-web-weekend-kathmandu.md
Adding the conference web weekend kathmandu to the list - https://2019.wwktm.co/
=> Add Web Weekend Kathmandu

site/conferences/2019-webclerks-vienna.md
A community-driven conference in Vienna, Austria.
=> Add webclerks conference 2019

site/conferences/2019-wordcamp-seattle.md
All info in PR. Let me know if anything needs to be changed.
Cheers!
Ryan
=> Add WordCamp Seattle

site/conferences/2020-halfstack-charlotte.md, site/conferences/2020-halfstack-london.md, site/conferences/2020-halfstack-newyork.md, site/conferences/2020-halfstack-phoenix.md, site/conferences/2020-halfstack-telaviv.md, site/conferences/2020-halfstack-vienna.md
-Event details
-dates
-location
-code of conduct
=> added events for halfstack conferences

site/conferences/2019-frontendne-newcastle.md
I know this is a past conference but I feel the location needed to be fixed 😅
=> Fix location error

site/conferences/2020-flashback-orlando.md
Adding the front end focused conference that I am running in February in Orlando.
=> Adding Flashback Conference

site/conferences/2020-reactloop-chicago.md
Surprisingly, I didn't go bankrupt last time so doing it again.  :)
=> Added React Loop 2020

site/conferences/2020-byteconf-graphql-online.md
Hey Chris + CSS Tricks team!
This PR adds Byteconf GraphQL, a free GraphQL conference live-streamed on YouTube: https://www.bytesized.xyz/graphql-2020
=> Add Byteconf GraphQL

site/conferences/2019-beyond-tellerrand-dusseldorf.md
=> Changed name to lower case

site/conferences/2020-csscamp-barcelona.md, site/conferences/2020-jscamp-barcelona.md
- dates correction for CSS Camp
- added JS Camp
=> CSS_Camp and JS_Camp

site/conferences/2020-front-end-north.md
Another conference. Thanks for the support.
=> Add Front End North

site/conferences/2020-jamstack-grabs-switzerland.md
Dear Chris
Kindly asking to add our JAMStack Conference to your liste.
With many thanks
Rolf.
=> JAMStack Conf Grabs Switzerland

site/conferences/2020-beyond-tellerrand-munich.md
=> Also here I must have written 2019 instead of 2020

site/conferences/2020-css-day-amsterdam.md
Our eighth edition is still missing :)
Thanks in advance!
=> Add CSS Day 2020

site/_data/site.json
=> Update site description year to 2020

site/conferences/2020-reactnativeeu-wroclaw.md
Thanks, have a nice weekend :)
=> Add ReactNativeEU 2020 conference

site/conferences/2020-frontconf-munich.md
=> Add Frontconf Munich

site/conferences/2020-PixelPioneers-Bristol.md
Added .md file for Pixel Pioneers in Bristol UK, 11-12 June 2020.
=> Added Pixel Pioneers

site/conferences/2020-render-atl.md
Updated the dates for Render-Atlanta 2020 due to the coronavirus pandemic
=> Updated Render-Atlanta dates

site/conferences/2020-JavaScriptandFriends-ColumbusOhio.md
Adding JavaScript and Friends Conference.
=> Created JavaScript and Friends Conference

LICENSE
Hi Chris - Per our discussion on Twitter, I'm sending you a pull request for an MIT license.  If I chose the wrong one, happy to change it.  Thanks again!
=> Creating a license file, and sending a pull request to Chris

site/conferences/2020-halfstack-charlotte.md, site/conferences/2020-halfstack-newyork.md, site/conferences/2020-halfstack-telaviv.md, site/conferences/2020-halfstack-vienna.md, site/conferences/2021-halfstack-newquay.md, site/conferences/2021-halfstack-phoenix.md
* Add HalfStack Newquay 2021
* Add HalfStack Phoenix 2021
* Correct date of HalfStack London 2020
* Update description of other HalfStack events
=> Various HalfStack updates and additions

site/conferences/2020-jsconf-korea.md
=> Add JSConf Korea

site/conferences/2021-render-atl.md
Added Render-Atlanta 2021 conference markdown file
=> Render-ATL .md file

site/conferences/2021-thejam-virtual.md
Adding a virtual conference coming this January.
=> Add TheJam.dev

site/conferences/2021-axe-con-virtual.md
Updates conference list with the axe-con 2021 digital accessibility conference.
=> Add axe-con 2021

site/conferences/2021-react-summit-remote.md
Updates conference list entries to include the 2021 React Summit.
=> Add React Summit 2021 remote edition

site/conferences/2021-code-pwas-2021.md, site/conferences/2021-globalscope-js-2021.md, site/conferences/2021-hover-css-2021.md, site/conferences/2021-lazyload-webperf-2021.md
4 new pages in site/comferemces for our 2021 events
=> Added Web Directions 2021 conferencs

site/conferences/2021-smashingmeets-online.md
Hi Chris and crew! We're running another event, would be great if you'd like to merge it in. 
Have a great day!
=> Added SmashingConf Meets in April 2021.

site/conferences/2021-dot-all-amsterdam.md
👋🏻  Here’s a cool event happening this year!
=> Dot All 2021

site/conferences/2022-javascriptandfriends.md
Adding JavaScript and Friends Conference 2022
=> Adding JavaScript and Friends Conference 2022

site/conferences/2022-aaa-accessibility.md, site/conferences/2022-code-pwas.md, site/conferences/2022-globalscope-js.md, site/conferences/2022-hover-css.md, site/conferences/2022-lazyload-webperf.md, site/conferences/2022-safe-security.md, site/conferences/2022-wd-summit.md
added web directions 2022 online and in person FE focussed events
=> Web Directions 2022

site/conferences/2022-render-atl.md
Updated copy & Dates for Render 2022
=> Updated Copy & Dates
